rootProject.name = "webservices"

include(":pipeline-common")
include(":knowledge-ingestion")
include(":embedding-worker")
include(":content-publisher")
include(":search-service")
include(":gpu-bootstrap-arbiter")
include(":gpu-workload-monitor")
include(":inference-gateway")
include(":inference-controller")
include(":test-manager")
include(":test-runner")
include(":workspace-provisioner")
include(":keycloak-onboarding-listener")
include(":chatgpt-connector")
include(":progression")

project(":pipeline-common").projectDir = file("stack.kotlin/pipeline-common")
project(":knowledge-ingestion").projectDir = file("stack.kotlin/knowledge-ingestion")
project(":embedding-worker").projectDir = file("stack.kotlin/embedding-worker")
project(":content-publisher").projectDir = file("stack.kotlin/content-publisher")
project(":search-service").projectDir = file("stack.kotlin/search-service")
project(":gpu-bootstrap-arbiter").projectDir = file("stack.kotlin/gpu-bootstrap-arbiter")
project(":gpu-workload-monitor").projectDir = file("stack.kotlin/gpu-workload-monitor")
project(":inference-gateway").projectDir = file("stack.kotlin/inference-gateway")
project(":inference-controller").projectDir = file("stack.kotlin/inference-controller")
project(":test-manager").projectDir = file("stack.kotlin/test-manager")
project(":test-runner").projectDir = file("stack.kotlin/test-runner")
project(":workspace-provisioner").projectDir = file("stack.kotlin/workspace-provisioner")
project(":keycloak-onboarding-listener").projectDir = file("stack.kotlin/keycloak-onboarding-listener")
project(":chatgpt-connector").projectDir = file("stack.kotlin/chatgpt-connector")
project(":progression").projectDir = file("stack.kotlin/progression")
