package org.webservices.pipeline.sources.standardized

import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import org.webservices.pipeline.core.Chunkable
import org.webservices.pipeline.core.StandardizedSource
import org.webservices.pipeline.processors.Chunker
import org.webservices.pipeline.scheduling.BackfillStrategy
import org.webservices.pipeline.scheduling.ResyncStrategy
import org.webservices.pipeline.scheduling.RunMetadata
import org.webservices.pipeline.scheduling.RunType
import org.webservices.pipeline.sinks.BookStackDocument
import org.webservices.pipeline.sources.AustralianLegalDocument
import org.webservices.pipeline.sources.OpenAustralianLegalCorpusSource


data class AustralianLegalDocumentChunkable(val doc: AustralianLegalDocument) : Chunkable {
    override fun toText(): String = doc.toText()
    override fun getId(): String = doc.id
    override fun getMetadata(): Map<String, String> = mapOf(
        "type" to doc.type,
        "jurisdiction" to doc.jurisdiction,
        "date" to doc.date,
        "citation" to doc.citation,
        "source" to doc.source,
        "url" to doc.url
    )

    fun toBookStackDocument(): BookStackDocument {
        val pageTitle = if (doc.citation.isNotBlank()) doc.citation else "${doc.type} (${doc.id})"
        return BookStackDocument(
            bookName = "Australian Legal Corpus",
            bookDescription = "Legal documents from Australian Commonwealth and State legislatures",
            chapterName = doc.jurisdiction,
            chapterDescription = "Legal documents from ${doc.jurisdiction}",
            pageTitle = pageTitle,
            pageContent = """
                <h1>${pageTitle}</h1>
                <div style="margin-bottom: 20px; padding: 15px; background-color: #fff3cd; border-left: 4px solid #ffc107;">
                    <p><strong>Type:</strong> ${doc.type}</p>
                    <p><strong>Jurisdiction:</strong> ${doc.jurisdiction}</p>
                    <p><strong>Date:</strong> ${doc.date}</p>
                    <p><strong>Citation:</strong> <code>${doc.citation}</code></p>
                    <p><strong>Source:</strong> <a href="${doc.url}" target="_blank">${doc.source}</a></p>
                </div>
                <div style="margin-top: 20px;">
                    <h2>Content</h2>
                    <div style="white-space: pre-wrap; word-wrap: break-word; font-family: 'Courier New', monospace; line-height: 1.5; background-color: #f8f9fa; padding: 15px; border-radius: 4px;">
                        ${doc.text.split("\n\n").joinToString("\n") { para ->
                            if (para.isNotBlank()) "<p>${para.replace("\n", " ")}</p>" else ""
                        }}
                    </div>
                </div>
                <hr>
                <p style="font-size: 0.9em; color: #666;">
                    <em>This page was automatically generated by webservices Pipeline from the Open Australian Legal Corpus.
                    Content sourced from ${doc.source} at <a href="${doc.url}" target="_blank">${doc.url}</a></em>
                </p>
            """.trimIndent(),
            tags = mapOf(
                "source" to "australian_laws",
                "jurisdiction" to doc.jurisdiction,
                "type" to doc.type,
                "date" to doc.date,
                "citation" to doc.citation
            )
        )
    }
}


class OpenAustralianLegalCorpusStandardizedSource(
    private val cacheDir: String = "/data/australian-legal-corpus",
    private val jurisdictions: List<String>? = null,  
    private val documentTypes: List<String>? = null,  
    private val maxDocuments: Int = Int.MAX_VALUE
) : StandardizedSource<AustralianLegalDocumentChunkable> {
    override val name = "australian_laws"

    
    override fun resyncStrategy() = ResyncStrategy.Monthly(dayOfMonth = 1, hour = 2, minute = 0)

    override fun backfillStrategy() = BackfillStrategy.LegalDatabase(
        jurisdictions = jurisdictions ?: listOf("all"),
        startYear = 1900  
    )

    override fun needsChunking() = true

    override fun chunker() = Chunker.forEmbeddingModel(tokenLimit = 8192, overlapPercent = 0.20)

    override suspend fun fetchForRun(metadata: RunMetadata): Flow<AustralianLegalDocumentChunkable> {
        
        

        val source = OpenAustralianLegalCorpusSource(
            cacheDir = cacheDir,
            filterJurisdictions = jurisdictions,
            filterTypes = documentTypes,
            maxDocuments = maxDocuments
        )

        return source.fetch().map { AustralianLegalDocumentChunkable(it) }
    }
}
