package org.webservices.pipeline.sources.standardized

import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import org.webservices.pipeline.core.Chunkable
import org.webservices.pipeline.core.StandardizedSource
import org.webservices.pipeline.scheduling.BackfillStrategy
import org.webservices.pipeline.scheduling.ResyncStrategy
import org.webservices.pipeline.scheduling.RunMetadata
import org.webservices.pipeline.scheduling.RunType
import org.webservices.pipeline.sinks.BookStackDocument
import org.webservices.pipeline.sources.RssArticle
import org.webservices.pipeline.sources.RssSource
import java.time.Instant
import java.time.temporal.ChronoUnit


class RssStandardizedSource(
    private val feedUrls: List<String>,
    private val backfillDays: Int = 7
) : StandardizedSource<RssChunkableArticle> {

    override val name = "rss"

    override fun resyncStrategy(): ResyncStrategy {
        
        return ResyncStrategy.Hourly(minute = 0)
    }

    override fun backfillStrategy(): BackfillStrategy {
        
        return BackfillStrategy.RssHistory(daysBack = backfillDays)
    }

    override fun needsChunking(): Boolean {
        
        
        return true
    }

    override suspend fun fetchForRun(metadata: RunMetadata): Flow<RssChunkableArticle> {
        val since = when (metadata.runType) {
            RunType.INITIAL_PULL -> {
                
                Instant.now().minus(backfillDays.toLong(), ChronoUnit.DAYS)
            }
            RunType.RESYNC -> {
                
                Instant.now().minus(1, ChronoUnit.HOURS)
            }
        }

        
        return org.webservices.pipeline.sources.RssSource(feedUrls)
            .fetch()
            .map { article -> RssChunkableArticle(article) }
    }
}


data class RssChunkableArticle(val article: RssArticle) : Chunkable {
    override fun toText(): String = article.toText()

    override fun getId(): String = article.guid

    override fun getMetadata(): Map<String, String> = buildMap {
        put("title", article.title)
        put("link", article.link)
        put("description", article.description.take(200))
        if (article.publishedDate.isNotEmpty()) put("published_date", article.publishedDate)
        if (article.author.isNotEmpty()) put("author", article.author)
        put("feed_title", article.feedTitle)
        put("feed_url", article.feedUrl)
        val categoriesStr = article.categories.joinToString(",")
        if (categoriesStr.isNotEmpty()) put("categories", categoriesStr)
        put("source", "rss")
    }

    fun toBookStackDocument(): BookStackDocument {
        
        val safeContent = article.content
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\"", "&quot;")

        return BookStackDocument(
            bookName = "RSS Feeds",
            bookDescription = "Aggregated news and blog feeds from various sources",
            chapterName = article.feedTitle,
            chapterDescription = "Articles from ${article.feedUrl}",
            pageTitle = article.title,
            pageContent = """
                <h1>${article.title}</h1>
                <div style="margin-bottom: 20px; padding: 10px; background-color: #f5f5f5; border-left: 4px solid #007bff;">
                    <p><strong>Source:</strong> <a href="${article.link}" target="_blank">${article.feedTitle}</a></p>
                    <p><strong>Published:</strong> ${article.publishedDate}</p>
                    ${if (article.author.isNotEmpty()) "<p><strong>Author:</strong> ${article.author}</p>" else ""}
                    ${if (article.categories.isNotEmpty()) "<p><strong>Categories:</strong> ${article.categories.joinToString(", ")}</p>" else ""}
                </div>
                <div style="margin-top: 20px;">
                    <h2>Summary</h2>
                    <p>${article.description}</p>
                </div>
                ${if (article.content.isNotEmpty() && article.content != article.description) """
                <div style="margin-top: 20px;">
                    <h2>Full Content</h2>
                    <pre style="white-space: pre-wrap; word-wrap: break-word;">${safeContent}</pre>
                </div>
                """ else ""}
                <hr>
                <p style="font-size: 0.9em; color: #666;">
                    <em>This page was automatically generated by webservices Pipeline from RSS feed: <a href="${article.feedUrl}" target="_blank">${article.feedUrl}</a></em>
                </p>
            """.trimIndent(),
            tags = mapOf(
                "source" to "rss",
                "feed" to article.feedTitle,
                "published" to article.publishedDate,
                "guid" to article.guid
            ) + if (article.author.isNotEmpty()) mapOf("author" to article.author) else emptyMap()
        )
    }
}
