package org.webservices.pipeline.core

import org.webservices.pipeline.sinks.BookStackDocument

/**
 * Interface for items that can be published to BookStack knowledge base.
 *
 * Integration points:
 * - BookStackWriter: Polls for COMPLETED documents and publishes via BookStack API
 * - BookStack API: Creates pages with HTML content in book/chapter hierarchy
 * - Search-Service: BookStack pages indexed alongside raw documents for hybrid search
 *
 * Design rationale:
 * - Separate interface from Chunkable because BookStack needs formatted HTML, not plain text
 * - Allows sources to define custom HTML rendering (metadata boxes, lists, formatting)
 * - BookStackDocument contains book/chapter/page structure for organizational hierarchy
 */
interface BookStackTransformable {
    /**
     * Converts item to BookStack page structure with HTML content.
     *
     * @return BookStackDocument with book/chapter/page hierarchy and HTML-formatted content
     */
    fun toBookStackDocument(): BookStackDocument
}

/**
 * Utility functions for generating consistent HTML content for BookStack pages.
 *
 * Integration points:
 * - BookStack API: Accepts HTML content (not Markdown)
 * - XSS prevention: All user content must be HTML-escaped before rendering
 * - Consistent styling: Shared CSS classes across all pipeline-generated pages
 *
 * Design rationale:
 * - Centralized HTML generation prevents XSS vulnerabilities
 * - Consistent formatting makes BookStack pages easily identifiable as pipeline-generated
 * - Reusable components (metadata boxes, lists) reduce duplication across sources
 */
object BookStackHtmlHelper {
    fun escapeHtml(text: String): String {
        return text
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\"", "&quot;")
            .replace("'", "&#39;")
    }

    fun sanitizeForHtml(text: String): String {
        
        return escapeHtml(text)
    }

    fun formatMetadataBox(items: List<Pair<String, String>>): String {
        return """
            <div style="margin-bottom: 20px; padding: 15px; background-color: #f8f9fa; border-left: 4px solid #007bff;">
                ${items.joinToString("\n") { (label, value) ->
                    "<p><strong>$label:</strong> $value</p>"
                }}
            </div>
        """.trimIndent()
    }

    fun formatListSection(title: String, items: List<String>, maxItems: Int = 50): String {
        if (items.isEmpty()) return ""

        val displayItems = items.take(maxItems)
        val remaining = items.size - maxItems

        return """
            <div style="margin-top: 20px;">
                <h2>$title</h2>
                <ul>
                    ${displayItems.joinToString("\n") { "<li>$it</li>" }}
                    ${if (remaining > 0) "<li><em>... and $remaining more</em></li>" else ""}
                </ul>
            </div>
        """.trimIndent()
    }

    fun formatFooter(sourceDescription: String): String {
        return """
            <hr>
            <p style="font-size: 0.9em; color: #666;">
                <em>This page was automatically generated by webservices Pipeline from $sourceDescription</em>
            </p>
        """.trimIndent()
    }
}
